# version: '3'
# services:
#   nginx:
#     restart: always
#     build:
#       dockerfile: dev.Dockerfile
#       context: ./Nginx
#     volumes:
#       - ./Nginx/logs:/var/log/nginx
#     ports:
#       - '80:80'
#
#
#   react-client:
#     build:
#       dockerfile: dev.Dockerfile
#       context: client
#     env_file:
#       - ./client/.env
#     volumes:
#       - /usr/app/node_modules
#       - ./clinet:/usr/app
#     command: ["npm","run","start"]

#   node-server:
#     build:
#       context: ./server
#       dockerfile: dev.Dockerfile
#     env_file:
#       - ./server/.env
#     volumes:
#       - /usr/app/node_modules
#       - ./server:/usr/app
#     command: ["npm", "run", "dev"]
#dd
version: "3.3"
services:
  nginx:
    image: nginx:latest # nginx 이미지
    container_name: web # 컨테이너 명
    restart: "on-failure" # 구동 실패 시 재시작
    ports:
      - 80:80
    volumes: # 볼륨 설정
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./client/build:/usr/share/nginx/html
  
  client:
    build: # Dockerfile 빌드
      context: ./client # Dockerfile 빌드 경로
    container_name: client # 컨테이너 명
    restart: "on-failure"
    volumes: # 볼륨 설정
      - './client:/app'
      - '/app/node_modules'
    expose:
      - 3000
    env_file:
      - ./client/.env
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  
  server:
    build: # Dockerfile 빌드
      context: ./server # Dockerfile 빌드 경로
    container_name: server # 컨테이너 명
    restart: "on-failure"
    ports:
      - "8080:8080"
    expose:
      - 8080 # 도커 내부적 포트
    volumes: # 볼륨 설정
      - './server:/app'
      - '/app/node_modules'
    env_file:
      - ./server/.env
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins_cicd
      restart: always
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - './jenkins_home:/var/jenkins_home'
      ports:
          - "9090:8080"
      privileged: true
      user: root